# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '要出发' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 要出发
pod 'AFNetworking'
pod 'MJRefresh'
pod 'Masonry'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'MBProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'MLTransition'
pod 'YYKit'
end
